export type SiteConfig = typeof siteConfig

export const siteConfig = {
  name: 'Create Next App',
  description: 'Generated by create next app.',
  mainNav: [
    {
      title: 'Home',
      href: '/',
    },
  ],
}
