export type SiteConfig = typeof siteConfig

export const siteConfig = {
  name: 'Create Next App',
  description: 'Generated by create next app.',
  mainNav: [
    {
      title: 'Dashboard',
      href: '/dashboard',
    },
  ],
  links: {
    docs: 'https://github.com/Garfield550/qstn-dct2/blob/main/README.md',
    github: 'https://github.com/Garfield550/qstn-dct2',
  },
}
